const filmes = [
  "Avengers",
  "Avatar",
  "Titanic",
  "Inception",
  "The Batman",
  "Iron Man",
  "Frozen",
  "Minions",
  "The Avengers",
  "Black Panther",
  "Deadpool",
  "The Lion King",
  "The Flash",
  "Spider-Man",
  "Joker",
  "Doctor Strange",
  "Interstellar",
  "Jurassic World",
  "The Meg",
  "John Wick",
  "Shazam",
  "Thor",
  "Transformers",
  "The Matrix",
  "The Dark Knight",
  "Guardians of the Galaxy",
  "The Hunger Games",
  "Coco",
  "Luca",
  "Encanto",
  "Cars",
  "Toy Story",
  "Up",
  "Finding Nemo",
  "Ratatouille",
  "Inside Out",
  "Turning Red",
  "Zootopia",
  "Moana 2",
  "The Secret Life of Pets",
  "Sing",
  "Despicable Me",
  "Kung Fu Panda",
  "How to Train Your Dragon",
  "Madagascar",
  "Puss in Boots",
  "Shrek",
  "Megamind",
  "The Boss Baby",
  "The Croods",
  "Hotel Transylvania",
  "The Lorax",
  "The Peanuts Movie",
  "The Good Dinosaur",
  "Big Hero 6",
  "Brave",
  "Wreck-It Ralph",
  "Tangled",
  "Bolt",
  "Rio",
  "Happy Feet",
  "Monster House",
  "Bee Movie",
  "Open Season",
  "The Polar Express",
  "Spirit",
  "Coraline",
  "ParaNorman",
  "The Nightmare Before Christmas",
  "A Bug's Life",
  "Chicken Run",
  "Wallace & Gromit",
  "Fantastic Mr. Fox",
  "The Lego Movie",
  "Kubo and the Two Strings",
  "Spider-Man Into the Spider-Verse",
  "Soul",
  "Raya and the Last Dragon",
  "The Bad Guys",
  "Wish",
  "Elemental",
  "Lyle Lyle Crocodile",
  "The Mitchells vs. The Machines",
  "Scoob!",
  "Trolls",
  "The Angry Birds Movie",
  "Epic",
  "Flushed Away",
  "Rise of the Guardians",
  "Storks",
  "Arthur Christmas",
  "Gladiator",
  "The Revenant",
  "Saving Private Ryan",
  "Braveheart",
  "Django Unchained",
  "The Wolf of Wall Street",
  "The Irishman",
  "The Godfather",
  "Pulp Fiction",
  "Fight Club",
  "Se7en",
  "The Silence of the Lambs",
  "Schindler's List",
  "Forrest Gump",
  "The Green Mile",
  "Cast Away",
  "The Departed",
  "Goodfellas",
  "A Beautiful Mind",
  "The Pianist",
  "Bohemian Rhapsody",
  "A Star Is Born",
  "Les Misérables",
  "The Social Network",
  "Catch Me If You Can",
  "The Prestige",
  "The Grand Budapest Hotel",
  "Knives Out",
  "No Country for Old Men",
  "There Will Be Blood",
  "American Sniper",
  "Zero Dark Thirty",
  "The Hurt Locker",
  "Gravity",
  "The Martian",
  "Looper",
  "Blade Runner 2049",
  "Mad Max Fury Road",
  "Logan",
  "The Equalizer",
  "The Bourne Identity",
  "Mission Impossible",
  "Skyfall",
  "Casino Royale",
  "The Dark Knight Rises",
  "The Shawshank Redemption",
  "1917",
  "Oppenheimer",
  "Dune"
];


export default filmes;
